version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
  cloudrun: circleci/gcp-cloud-run@1.0.1
  gcp-cli: circleci/gcp-cli@2.1
  docker: circleci/docker@2.2.0

executors:

  gcloud-executor:
    docker:
      - image: google/cloud-sdk
  machine-executor:
    machine: true
jobs:
    build:
        docker:
            - image: maven:3.8.1-openjdk-17-slim
        environment:
          MAVEN_CLI_OPTS: "--batch-mode"
        steps:
            - checkout
            - run: mvn $MAVEN_CLI_OPTS -Dvaadin.offlineKey="eyJraWQiOiI1NDI3NjRlNzAwMDkwOGU2NWRjM2ZjMWRhYmY0ZTJjZDI4OTY2NzU4IiwidHlwIjoiSldUIiwiYWxnIjoiRVM1MTIifQ.eyJhbGxvd2VkUHJvZHVjdHMiOlsidmFhZGluLWNoYXJ0cyIsInZhYWRpbi10ZXN0YmVuY2giLCJ2YWFkaW4tZGVzaWduZXIiLCJ2YWFkaW4tY2hhcnQiLCJ2YWFkaW4tYm9hcmQiLCJ2YWFkaW4tY29uZmlybS1kaWFsb2ciLCJ2YWFkaW4tY29va2llLWNvbnNlbnQiLCJ2YWFkaW4tcmljaC10ZXh0LWVkaXRvciIsInZhYWRpbi1ncmlkLXBybyIsInZhYWRpbi1tYXAiLCJ2YWFkaW4tc3ByZWFkc2hlZXQtZmxvdyIsInZhYWRpbi1jcnVkIiwidmFhZGluLWNvcGlsb3QiLCJ2YWFkaW4tZGFzaGJvYXJkIl0sInN1YiI6IjE4NzQwNDRhLTVmYWEtNDE2NC1iY2EyLWNlZDkxMzE3ZjczYyIsInZlciI6MSwiaXNzIjoiVmFhZGluIiwiYWxsb3dlZEZlYXR1cmVzIjpbImNlcnRpZmljYXRpb25zIiwic3ByZWFkc2hlZXQiLCJ0ZXN0YmVuY2giLCJkZXNpZ25lciIsImNoYXJ0cyIsImJvYXJkIiwiYXBwc3RhcnRlciIsInZpZGVvdHJhaW5pbmciLCJwcm8tcHJvZHVjdHMtMjAyMjEwIl0sIm1hY2hpbmVfaWQiOm51bGwsInN1YnNjcmlwdGlvbiI6IlZhYWRpbiBQcm8iLCJzdWJzY3JpcHRpb25LZXkiOm51bGwsIm5hbWUiOiJTdWdhbnRoaSBNYW5vaGFyYW4iLCJidWlsZF90eXBlcyI6WyJwcm9kdWN0aW9uIl0sImV4cCI6MTc1MDQ2NDAwMCwiaWF0IjoxNzQ1NTA0NDk3LCJhY2NvdW50IjoiTWFuYWdlbWVudCBDZW50ZXIgSW5uc2JydWNrIn0.AFyQZwoitcBcvxGnFu0wrMo3oDV2Z31zHAYa83YRsC1i31xBcdJAkIHEkYDFa-azCHrWhmHT_5g1pKnmX7mrEFfyAdmjb6qHD9O4zhCtlV5mmjVCKZIdwWXPI2FIUFoCEOdIDS7URw9Xy0KdBya1OnO8rY75o8BrMbIdYFWwJvp4d9jC" clean package -Pproduction -e
            - store_artifacts:
                path: target
                destination: target
                
    test:
        docker:
            - image: maven:3.8.1-openjdk-17-slim
        steps:
            - checkout
            - run: mvn test -e
            - store_artifacts:
                path: reports
                destination: reports   
jobs:
  build-docker-image:
    executor:
      name: docker/docker
      tag: "3.6"
    steps:
      - checkout
      - docker/install-docker-tools
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t vaadincrapplicaton.azurecr.io/VaadinCRapplicaton:latest .
            echo $DOCKER_PASS | docker login dockerdotnetcoreapi.azurecr.io -u $DOCKER_USER --password-stdin
            docker push dockerdotnetcoreapi.azurecr.io/dotnet-api:latest
               
         
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test:
          requires:
            - build
  - build-and-deploy:
    jobs:
      - build-docker-image 
